""" This file stores dirty heuristic groups and list

"""

GROUP_DICT = {      # Low frequency
    "NavigationDataSet": {
        "Timestamp",
        "State",
        "Event",
        "Position",
        "ETA",
        "Period",
        "Sailing Time",
        "Heading",
        "Course Made Good",
        "Speed Over Ground",
        "Speed Through Water",
        "Distance Over Ground",
        "Distance Through Water",
        "Water Depth",
        "Water Depth Below Keel",
        "AVG Speed Over Ground",
        "Displacement",
        "Draft Forward",
        "Draft Aft",
        "Mean Draft",
        "Trim",
        "Ballast Weight"},
    "Gerneral": {
        "Captain",
        "Chief Engineer",
        "Cargo Weight",
        "Cargo TEU full",
        "Cargo TEU empty",
        "Cargo Reefers"},
    "AirAndWater": {
        "Sea Water Temp",
        "Sea Water Temp (Weather Provider)",
        "Air Temp",
        "Air Temp (Weather Provider)",
        "Air Press",
        "Air Press (Weather Provider)",
        "Visibility (Weather Provider)"},
    "Wind": {
        "Wind Force",
        "Wind Speed True",
        "Wind Speed True (Weather Provider)",
        "Wind Speed Rel.",
        "Wind Direction True",
        "Wind Direction True (Weather Provider)",
        "Wind Direction Rel."},
    "Current": {"Current Factor"},
    "Waves": {
        "Sea State",
        "Wave Height",
        "Wave Height (Weather Provider)",
        "Wave Direction",
        "Swell Height",
        "Swell Height (Weather Provider)",
        "Swell Direction",
        "Swell Direction (Weather Provider)",
        "Swell Period (Weather Provider)"},
    "MachineryGeneralData": {
        "Engine Distance",
        "Total Running Hours ME",
        "AVG Shaft RPM",
        "AVG Slip Through Water",
        "AVG Slip Over Ground"},
    "FuelOilConsumption": {
        "Total FOC",
        "Total FOC (ISO)",
        "Total Daily FOC",
        "Total FOC HFO",
        "Total FOC HFO HS",
        "Total FOC HFO LS",
        "ME HFO Sulphur Content",
        "Total FOC MDO",
        "Total FOC MGO"},
    "MainEngine": {
        "Total Power ME (AVG)",
        "ME Load (AVG)",
        "Total Generated Energy ME",
        "Total Shaft Power (AVG)",
        "Total Generated Shaft Energy",
        "Total FOC ME",
        "Total FOC ME (ISO)",
        "Daily ME FOC",
        "Total SFOC ME",
        "Total SFOC ME (ISO)"},
    "AuxiliaryEngines": {
        "Total Power AE (AVG)",
        "AE Load (AVG)",
        "Total Generated Energy AE",
        "Total Generated Electrical Energy",
        "Total Electrical Power (AVG)",
        "AE Generator Load (AVG)",
        "Total FOC AE",
        "Total FOC AE (ISO)",
        "Daily AE FOC",
        "Total SFOC AE",
        "Total SFOC AE (ISO)"},
    "KPI": {
        "EEOI (TEU)",
        "EEOI (Weight)",
        "Transport Efficiency"},
    "Emissions": {
        "Total CO2",
        "Total CO2 ME",
        "Total CO2 AE",
        "Total CO2 AB",
        "Total NOx Emissions",
        "ME NOx Emissions",
        "AE NOx Emissions",
        "Boiler NOx Emissions",
        "Total SOx Emissions",
        "ME SOx Emissions",
        "AE SOx Emissions",
        "Boiler SOx Emissions",
        "Is on Scrubber Mode"},
    "AuxiliaryBoiler": {
        "Total FOC AB",
        "Total FOC AB (ISO)",
        "Daily AB FOC"}}

GROUP_DICT_M = {    # Middle frequency
    "NavigationDataSet": {
        "Timestamp (UTC)",
        "rel_to_leg_betw",
        "latitude",
        "longitude",
        "sog_kn",
        "cog_deg",
        "heading_deg",
        "rot_deg_min",
        "Status",
        "nav_status",
        "draught_m"},
    "Gerneral": {},
    "AirAndWater": {
        "air_rel_humidity_pct",
        "air_pressure_msl_pa",
        "air_temp_c",
        "water_temp_c",
        "salinity_pct"},
    "Wind": {
        "wind_guast_at_surface_m_s",
        "wind_speed_m_s",
        "wind_direction_deg",
        "wind_u_cmp",
        "wind_v_cmp"},
    "Current": {"current_direction_deg",
        "current_speed_m_s",
        "current_u_cmp",
        "current_v_cmp"},
    "Waves": {
        "primary_wave_direction_deg",
        "primary_wave_period_s",
        "secondary_wave_direction_deg",
        "secondary_wave_period_s",
        "wind_wave_direction_deg",
        "wind_wave_period_s",
        "sign_height_comb_wave_swell_m",
        "surface_elevation_m"},
    "MachineryGeneralData": {},
    "FuelOilConsumption": {
        "total_foc_in_15_min",
        "total_foc_iso_in_15_min"},
    "MainEngine": {
        "me_total_foc_in_15_min",
        "me_total_foc_iso_in_15_min"},
    "AuxiliaryEngines": {},
    "KPI": {},
    "Emissions": {},
    "AuxiliaryBoiler": {}}


GROUP_DICT_H = {    # High frequency
    "NavigationDataSet": {
        "entry_date", 
        "rel_to_leg_betw.", 
        "sa_spd_act_rpm", 
        "v_sog_act_kn", 
        "v_stw_act_kn", 
        "dsi_aftcl_act_m", 
        "dsi_fwdcl_act_m", 
        "v_dog_cnt_tot_nm", 
        "v_slpog_act_prc", 
        "wea_wsr_act_mps", 
        "wea_wdr_act_deg", 
        "v_rua_act_avg_deg", 
        "v_wd_act_m", 
        "v_cog_act_deg",
        "v_hdg_act_deg", 
        "v_rot_act_deg_min",
        # Don't have a clue for the variables below..
        "wea_wdt_act_deg", 
        "wea_wdtv_act_deg", 
        "wea_wst_act_mps", 
        "dsi_midps_act_m", 
        "dsi_midsb_act_m", 
        "v_dtw_cnt_tot_nm", 
        "v_slptw_act_prc", 
        "v_sfctw_act_kg_nm", 
        "v_sfcog_act_kg_nm"},
    "Gerneral": {},
    "AirAndWater": {},
    "Wind": {},
    "Current": {},
    "Waves": {},
    "MachineryGeneralData": {},
    "FuelOilConsumption": {},
    "MainEngine": {
        "me_pow_act_kw", 
        "me_fms_act_t_h", 
        "me_tqu_act_knm",
        "me_lod_act_prc", 
        "me_eff_act_prc", 
        "me_sfc_act_g_kwh", 
        "me_sfci_act_g_kwh"},
    "AuxiliaryEngines": {},
    "KPI": {},
    "Emissions": {},
    "AuxiliaryBoiler": {}}


EXCLUDE_REPLACE_NULL_LIST = ["sailing time", "distance over ground",
                             "distance through water", "avg speed",
                             "speed through water", "speed over ground"]

EXCLUDE_OD_LIST = ["period", "sailing time", "distance over ground",
                   "distance through water", "avg speed", 
                   "speed through water", "speed over ground"]

EXCLUDE_IMPUTE_LIST = ["period", "sailing time", "distance over ground",
                   "distance through water", "avg speed", 
                   "speed through water", "speed over ground"]
